# Generated by Django 6.0 on 2025-12-31 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('address_cep', models.CharField(blank=True, max_length=10, null=True)),
                ('address_street', models.CharField(blank=True, max_length=200, null=True)),
                ('address_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa Entrega')),
                ('observation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_preparo', 'Em Preparo'), ('saiu_entrega', 'Saiu para Entrega'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenants.order')),
            ],
        ),
    ]
