# Generated by Django 6.0 on 2025-12-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Impresso?'),
        ),
    ]
