# Generated by Django 6.0 on 2025-12-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_order_is_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='opening_hours',
            field=models.CharField(blank=True, default='Seg-Dom: 18h às 23h', max_length=200, null=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pix_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade PIX'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pix_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pix_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Titular PIX'),
        ),
    ]
