# Generated by Django 6.0 on 2025-12-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_address_tenant_opening_hours_tenant_pix_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta (Ex: Mais Vendido)'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Original (De)'),
        ),
    ]
