# Generated by Django 6.0 on 2025-12-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Loja Aberta?'),
        ),
    ]
