# Generated by Django 6.0 on 2025-12-31 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')])),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Abertura')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Fechamento')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fechado neste dia?')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_days', to='tenants.tenant')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('tenant', 'day')},
            },
        ),
    ]
