# Generated by Django 6.0 on 2025-12-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_operatingday'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='manual_override',
            field=models.BooleanField(default=False, verbose_name='Fechamento Manual?'),
        ),
    ]
