# Generated by Django 6.0 on 2025-12-31 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_manual_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa de Entrega')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fees', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'neighborhood')},
            },
        ),
    ]
