# Generated by Django 6.0 on 2025-12-31 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_deliveryfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Grupo')),
                ('type', models.CharField(choices=[('radio', 'Escolha Única (Ex: Ponto da carne)'), ('checkbox', 'Múltipla Escolha (Ex: Adicionais)')], default='checkbox', max_length=20)),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório?')),
                ('max_quantity', models.IntegerField(default=1, help_text='Para múltipla escolha', verbose_name='Máximo de itens')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tenants.product')),
            ],
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Opção')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Adicional')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenants.productoption')),
            ],
        ),
    ]
