# Generated by Django 6.0 on 2025-12-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_productoption_optionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='options_text',
            field=models.TextField(blank=True, null=True, verbose_name='Opcionais Selecionados'),
        ),
    ]
