# Generated by Django 6.0 on 2025-12-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_orderitem_options_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: PRIMEIRACOMPRA10', max_length=20, verbose_name='Código do Cupom')),
                ('description', models.CharField(blank=True, help_text='Ex: 10% off na primeira compra', max_length=200, null=True, verbose_name='Descrição')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentagem (%)'), ('fixed', 'Valor Fixo (R$)')], default='percentage', max_length=20, verbose_name='Tipo de Desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Desconto')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Pedidos abaixo deste valor não podem usar este cupom', max_digits=10, verbose_name='Valor Mínimo do Pedido')),
                ('usage_limit', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Limite de Uso')),
                ('used_count', models.IntegerField(default=0, verbose_name='Vezes Usado')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido a partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tenants.tenant', verbose_name='Loja')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenants.coupon', verbose_name='Cupom Usado'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Usado em')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto Aplicado')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='tenants.coupon', verbose_name='Cupom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='tenants.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Uso de Cupom',
                'verbose_name_plural': 'Usos de Cupom',
            },
        ),
    ]
