# Generated by Django 4.2.27 on 2026-01-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_order_discount_value_coupon_order_coupon_couponusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='opening_hours',
        ),
    ]
