# Generated by Django 6.0 on 2026-01-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_remove_tenant_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Ex: pizzariadoze.com.br (sem http:// ou www)', max_length=255, null=True, unique=True, verbose_name='Domínio Personalizado'),
        ),
    ]
