# Generated by Django 6.0 on 2026-01-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_tenant_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='delivery_time',
            field=models.IntegerField(default=45, help_text='Tempo estimado para entrega em minutos. Ex: 45', verbose_name='Tempo de Entrega (minutos)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pickup_time',
            field=models.IntegerField(default=25, help_text='Tempo estimado para retirada em minutos. Ex: 25', verbose_name='Tempo de Retirada (minutos)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_delivery_time',
            field=models.BooleanField(default=True, help_text='Exibir o tempo de entrega estimado na página do cardápio', verbose_name='Mostrar Tempo de Entrega?'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_pickup_time',
            field=models.BooleanField(default=True, help_text='Exibir o tempo de retirada estimado na página do cardápio', verbose_name='Mostrar Tempo de Retirada?'),
        ),
    ]
