# Generated by Django 6.0 on 2026-01-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_tenant_delivery_time_tenant_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Retirada'), ('table', 'Mesa')], default='delivery', max_length=20, verbose_name='Tipo de Pedido'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número da Mesa')),
                ('capacity', models.IntegerField(default=4, verbose_name='Capacidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='tables_qr/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tenants.tenant', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenants.table', verbose_name='Mesa'),
        ),
    ]
