# Generated by Django 6.0 on 2026-01-09 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_order_order_type_table_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Plano Starter'), ('pro', 'Plano Pro')], default='starter', max_length=20, verbose_name='Tipo de Plano'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_active',
            field=models.BooleanField(default=True, verbose_name='Assinatura Ativa?'),
        ),
    ]
