# Generated by Django 6.0 on 2026-01-09 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_tenant_created_at_tenant_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Válido Até'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
    ]
