# Generated by Django 6.0 on 2026-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_tenant_valid_until_alter_tenant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#ea580c', help_text='Cor Hex. Ex: #FF0000', max_length=7, verbose_name='Cor Primária'),
        ),
    ]
