# Generated by Django 6.0 on 2026-01-17 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_alter_tenant_primary_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('type', models.CharField(choices=[('radio', 'Escolha Única (Ex: Ponto da carne)'), ('checkbox', 'Múltipla Escolha (Ex: Adicionais)')], default='checkbox', max_length=20, verbose_name='Tipo de Seleção')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório?')),
                ('max_quantity', models.IntegerField(default=10, help_text='Para múltipla escolha', verbose_name='Máximo de itens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Grupo de Produtos',
                'verbose_name_plural': 'Grupos de Produtos',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productoption',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_options', to='tenants.productgroup', verbose_name='Grupo Origem'),
        ),
        migrations.CreateModel(
            name='GroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Opção')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Adicional')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenants.productgroup')),
            ],
            options={
                'unique_together': {('group', 'name')},
            },
        ),
    ]
