# Generated by Django 6.0 on 2026-01-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_productgroup_productoption_group_groupitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=200, verbose_name='Chave P256dh')),
                ('auth', models.CharField(max_length=200, verbose_name='Chave Auth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='tenants.tenant', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Subscription Push',
                'verbose_name_plural': 'Subscriptions Push',
                'unique_together': {('tenant', 'endpoint')},
            },
        ),
    ]
