# Generated by Django 6.0 on 2026-01-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_pushsubscription_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Cliente'),
        ),
    ]
