# Generated by Django 6.0 on 2026-01-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_pushsubscription_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
    ]
