# Generated by Django 6.0 on 2026-01-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_alter_tenant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='É agendamento?'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Agendada'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Agendada'),
        ),
    ]
