# Generated by Django 6.0 on 2026-01-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_order_is_scheduled_order_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_scheduling',
            field=models.BooleanField(default=True, verbose_name='Permitir Agendamento?'),
        ),
    ]
