# Generated by Django 6.0 on 2026-01-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_tenant_allow_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mercadopago_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transação MP'),
        ),
        migrations.AddField(
            model_name='order',
            name='mercadopago_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status MP'),
        ),
        migrations.AddField(
            model_name='order',
            name='pix_qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='QR Code (Base64)'),
        ),
        migrations.AddField(
            model_name='order',
            name='pix_qr_code_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Imagem QR (Base64)'),
        ),
        migrations.AddField(
            model_name='order',
            name='pix_ticket_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Ticket'),
        ),
        migrations.CreateModel(
            name='TenantPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='Refresh Token')),
                ('public_key', models.CharField(max_length=255, verbose_name='Public Key')),
                ('account_id', models.CharField(max_length=100, verbose_name='ID da Conta MP')),
                ('expires_in', models.IntegerField(verbose_name='Expira em (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='tenants.tenant', verbose_name='Loja')),
            ],
        ),
    ]
